export const SHOW_MODAL_LOGIN="SHOW_MODAL_LOGIN";
export const SHOW_MODAL_REGISTER="SHOW_MODAL_REGISTER";
export const CLOSE_MODAL_LOGIN="CLOSE_MODAL_LOGIN";
export const ADD_TO_CART="ADD_TO_CART";
export const CHANGE_QUANTITY_CART="CHANGE_QUANTITY_CART";
export const DELETE_CART_ITEM="DELETE_CART_ITEM";
